#!/usr/bin/env php
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace MagentoDevBox;

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/command/MagentoSetup.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->addCommands(
    [
        new Command\MagentoSetup()
    ]
);
$application->run();
